### ISSUE TITLE
Upcoming CMAP report changes.

### ISSUE THREAD

**Issue by adam-zabinski** [cmapsoftware/CMAP-API#8]
Pull new field from the CSV report called "Core opportunity value" and use for calculation instead of total project value. 

If "COV" < "Won" then replace COV with WON value. 

Review project status field in the end report. (when won && lost should still show as won).

**Comment by cmap-gaz** [comment]
Hi Adam

Can I just check which part of the API this comment relates to?

**Comment by adam-zabinski** [comment]
This is embarrassing. WAs supposed to submit that under our implementation of your API. Apologies
